Rails.application.routes.draw do
  get 'departamento/listadepartamento'
  get 'departamento/registrodepartamento'
  get 'proyecto/listaProyecto'
  get 'proyecto/registroProyecto'
  get 'usuario/listaUsuario'
  get 'usuario/registroUsuario'
  get 'reporte/reporte'
  get 'venta/registroVenta'
  get 'separacion/registroSeparacion'
  get 'cotizacion/listaCotizacion'
  get 'cotizacion/registroCotizacion'
  get 'cita/listaCita'
  get 'cita/detalleCita'
  get 'login/login'
  get 'proyectos_cliente/listaProyectoCliente'
  get 'proyectos_cliente/listaDepartamentoCliente'
  get 'proyectos_cliente/detalleDepartamento'
  get 'proyectos_cliente/solicitarCita'
  get 'page_estatica/nosotros'
  get 'page_estatica/contactUs'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
